version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '05:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 100
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'dependencies ->'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '05:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 100
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'ci-other ->'
