name: Versioning
description: Generates usefull versioning info
inputs:
  track:
    description: The version track to use for this version
    required: true
    default: ${{ github.ref.split('/').last }}
  token:
    description: Token to use for Authentication
    required: true
    default: ${{ github.token }}
outputs:
  version:
    description: JSON with version information
runs:
  using: node12
  main: "dist/index.js"
