on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Setup Firebase
        run: |
          curl -sL https://firebase.tools | bash
      - name: perform checks
        run: |
          cd functions
          npm install
          npm run lint
          npm run coverage
          npm run test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: functions/coverage
