name: Create Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Versioning
        id: versioning
        uses: ./.github/actions/self
        with:
          version_template: '<<VERSION_STRING>>'
          create: false
          track: main
          token: ${{ secrets.TOKEN_GITHUB_RELEASES }}
      - name: Write version.json
        run: echo '${{ steps.versioning.outputs.version }}' > version.json
      - name: Create Release
        uses: actions/github-script@v4
        with:
          script: |
            const { readFileSync } = require('fs');
            const { resolve } = require('path');

            const version = JSON.parse(readFileSync(resolve(__dirname, '../..', 'version.json')))
            const content = readFileSync(resolve(__dirname, '../..', 'action.yml'), 'utf-8').replace(
              'ghcr.io/onezerocompany/versioning-action:latest',
              `ghcr.io/onezerocompany/versioning-action:${version.version.versionString}`
            );

            const mainBranch = await github.rest.git.getRef({
              ...context.repo,
              ref: 'heads/main'
            })

            await github.rest.git.createRef({
              ...context.repo,
              ref: `refs/heads/${ version.version.versionString }`,
              sha: mainBranch.object.sha
            })

            const fileSha = (await github.rest.repos.getContent({
              ...context.repo,
              path: 'action.yml'
            })).sha

            await github.rest.repos.createOrUpdateFileContents({
              ...context.repo,
              path: 'action.yml',
              message: 'updated docker version',
              content,
              sha: fileSha,
              branch: version.version.versionString
            })

            const release = await github.rest.repos.createRelease({
              ...context.repo,
              name: version.version.versionString,
              tag_name: version.version.versionString,
              body: `${version.changelogs.public.content}${
                version.changelogs.private.hasChanges
                  ? `\n---\n${version.changelogs.private.content}`
                  : ''
              }`,
              target_commitish: version.version.versionString,
            });

            await github.rest.repos.uploadReleaseAsset({
              ...context.repo,
              release_id: release.data.id,
              name: 'version.json',
              data: JSON.stringify(version),
            });

            await github.rest.git.deleteRef({
              ...context.repo,
              ref: `refs/heads/${ version.version.versionString }`
            })
