name: Publish
on:
  release:
    types: [published]

jobs:
  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Version Details
        id: version
        uses: ./../../details
        with:
          version: ${{ github.event.release.name }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags:
            ghcr.io/onezerocompany/versioning-action:${{ github.event.release.name }}
            ghcr.io/onezerocompany/versioning-action:v${{ steps.run_tests.outputs.version_major }}
            ghcr.io/onezerocompany/versioning-action:latest
  npm:
    name: NPM & GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm install
      - name: Set Version
        run: npm --no-git-tag-version version "${{ github.event.release.name }}"
      - name: Set Name
        run: npm config set name="@onezerocompany/verify-commit-message"
      - name: Build Message Validator
        run: npm run build:validator
      - name: Setup for GitHub Packages
        uses: actions/setup-node@v3.0.0
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@onezerocompany'
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB_RELEASES }}
