name: Versioning
on:
  push:
    branches:
      - release
      - beta
      - alpha
jobs:
  generate_version:
    runs-on: ubuntu-latest
    steps:
      - id: generate_version
        name: Generate Version.json
        uses: ./
      - run: echo '${{ steps.generate_version.outputs.version }}' > version.json
      - name: Upload Version.json
        uses: actions/upload-artifact@v2
        with:
          name: version.json
          path: version.json
          retention-days: 1
